### ISSUE TITLE
Meaning of (x_1,y_1,x_2,y_2) in bbox annotation.

### ISSUE THREAD

**Issue by PengxinWang** [ilnehc96/HKU-DASC7606-A1#1]
In the dataloader.py file, we're required to tranform the bbox annotation, but I'm not sure about the meaning of the representation, does (x,y), (x1,y1) mean the top-left corner of the bbox and (x2,y2) the bottom-right corner of that, which implies that h is a negative number? Does this a typical convetion of bbox annotation? 
# TODO: Please substitute the "?" to transform annotations from [x, y, w, h] to [x1, y1, x2, y2]`

**Comment by ilnehc96** [comment]
> (x1,y1) mean the top-left corner of the bbox and (x2,y2) the bottom-right corner 

Yes. Please see [COCO Format](https://cocodataset.org/#format-data): 1. Object Detection.

`w` and `h` are not negative, as "In addition, an enclosing bounding box is provided for each object (box coordinates are measured from the top left image corner and are 0-indexed)"

**Comment by PengxinWang** [comment]
Thank you very much! It seems that measuring from top left can make it eaiser to calculate IoU.
