### ISSUE TITLE
How to generate model_link.txt

### ISSUE THREAD

**Issue by aricl3** [ilnehc96/HKU-DASC7606-A1#13]
I have made model but it is too large to upload. I want to know which tool or method to use to upload models?

**Comment by ilnehc96** [comment]
You should upload it to the cloud and provide the share link in the text file.

**Comment by aricl3** [comment]
Can I use Baidu Netdisk Or Google Netdisk?

**Comment by ilnehc96** [comment]
Google Drive or OneDrive would be better.

**Comment by aricl3** [comment]
I have trained several models with different performance. Should I upload the model with the best performance or upload them all?

**Comment by ilnehc96** [comment]
Please see instructions about the bonus part. At least you need the default one, and a best one which you would like to have it for test evaluation. You need to state clearly in a README file.

**Comment by tengwang0318** [comment]
> Please see instructions about the bonus part. At least you need the default one, and a best one which you would like to have it for test evaluation. You need to state clearly in a README file.

@ilnehc96  If I don't change the model part and improve the performance by data augmentation and something else, what does model_link.txt need? The origin code without any improvement or the origin model with improvement?

**Comment by ilnehc96** [comment]
the checkpoint. model_final.pt
