### ISSUE TITLE
Expected time for file compression takes another 23 hours

### ISSUE THREAD

**Issue by hkcoserlamyiupong** [ilnehc96/HKU-DASC7606-A1#18]
![image](https://github.com/ilnehc96/HKU-DASC7606-A1/assets/63230294/59007324-c871-4d8c-936a-78b94cb0bd9c)
Dear Teachers, yesterday when I tried to compress my HKU-DASC7606-A1 into a zip file and then rename it to my UID, it suddenly appeared that it is expected to take another 23 hours just for the file compression. May I ask what should I do?

**Comment by hkcoserlamyiupong** [comment]
![image](https://github.com/ilnehc96/HKU-DASC7606-A1/assets/63230294/11e45189-5ff3-41ec-94e9-cd6f882d83de)
Furthermore, I have tried to upload another smaller (.zip) file to the moodle and found that the moodel submission system is also hang.

**Comment by hkcoserlamyiupong** [comment]
Moodle just says that my file was too large to be submitted. May I submit it by other methods?

**Comment by ilnehc96** [comment]
@hkcoserlamyiupong 
Pls remove unnecessary files, such as data/ folder, output/ folder, resnet.pth. The file size limitation on Moodle is set to 50MB. It should be way enough if you correctly clean up.

You are compressing the checkpoint as well, as shown in your screenshot. Checkpoint should be submitted as a share link of Google Drive or OneDrive. Pls see Issue doc and Moodle announcement for details.

We do not accept email submission. Pls submit via Moodle.

**Comment by hkcoserlamyiupong** [comment]
Thank you very much. I have finally compressed the file and uploaded to moodle after file deletion.
