### ISSUE TITLE
files organization

### ISSUE THREAD

**Issue by hkcoserlamyiupong** [ilnehc96/HKU-DASC7606-A1#7]
After we git clone https://github.com/ilnehc96/HKU-DASC7606-A1.git
 cd HKU-DASC7606-A1
As we are told to 'After downloading and extracting the dataset, you should put all files following the structure
 below:', may I ask several questions regarding the structure ambiguity?
Firstly, inside the outermost 'HKU-DASC7606-A1', besides the required  retinanet, train.py, test.py, test_submission.py, vis.py and README.md, there should also be two directories, namely 'output' and 'sources' with a vis.png inside.
Secondly, the directory 'image' inside 'data' is actually named as 'images' in the original trainval Google drive given to us.
Should we rename 'images' as 'image' instead?
Lastly, from the instruction 'If your student id is 12345, then the compressed file for submission on Moodle should be
 organized as follows:', it seems that our final submitted format and file structure is very different compared with our given files.
May I ask what are the different functions and content we should put correspondingly in the (optional) README.md, (optioinal) source code for bonus, (optioinal) bonus_model_link.txt, (optioinal bonus) bonus_test_bbox_results.json, your source code and model_link.txt?
I know we are required to improve the baseline model with your own configuration, but I don't know where should I put the modification and what is the difference between newly created different files to be submitted.
For 'All the completed codes.' should we put the whole given 'HKU-DASC7606-A1' directory together in the same location with report.pdf, model_link.txt, test_bbox_results.json, ... and zip them together into 3035691248.zip /.tar /.tar.gz?
What does it mean by 'Models, in the format of model checkpoint link (model_link.txt) due to the limitation on
 submission file size.'? (Isn't models stored as 'class ResNet(nn.Module):'... inside the original model.py? How can we implement another model using a txt file instead of defining it as a class inside the original python file?)
After producing test_bbox_results.json, may we reproduce bonus_test_bbox_results.json simply by editing the codes in the original python files, and then rename another test_bbox_results.json into the bonus_test_bbox_results.json?

**Comment by ilnehc96** [comment]
1. Sorry. should be `images` instead of `image`.
2. The original codebase (HKU-DASC7606-A1) corresponds to the source code.
3. Bonus part are identical to the given part, eg bonus source code should be a separate codebase. Bonus part is for other models which are largely different from ours.
4. If you improved in the given codebase, you are just fine to not provide another codebase. It is also fine to have a single results json file.
5. The model for submission means the saved checkpoint.

**Comment by tengwang0318** [comment]
@ilnehc96 May I ask what model_link.txt stands for? Should we upload the model parameters pth file into a platform like Google Driver and share that?

**Comment by lunachern** [comment]
Same question. Should we save model_final.py as .ckpt?

**Comment by ilnehc96** [comment]
> @ilnehc96 May I ask what model_link.txt stands for? Should we upload the model parameters pth file into a platform like Google Driver and share that?

@tengwang0318 @lunachern Yes. Upload ckpt file to a drive, and put the share link in the txt file.
