### ISSUE TITLE
too long runtime that the school gpu automatically disconnect

### ISSUE THREAD

**Issue by hkcoserlamyiupong** [ilnehc96/HKU-DASC7606-A1#8]
After filling in the blanks and trying to run python train.py --coco_path ./data --output_path ./output --depth 50 --epochs 20
it takes too long that the school gpu automatically disconnect (it happens again when I attempted to reconnect and run this command line again.) what should I do?

![螢幕擷取畫面 2024-02-26 001555](https://github.com/ilnehc96/HKU-DASC7606-A1/assets/63230294/c18ab7e4-8f06-4697-92d3-3eb99cd45917)

![image](https://github.com/ilnehc96/HKU-DASC7606-A1/assets/63230294/748aefc6-2ceb-4a79-ba26-31136f803a35)

**Comment by A135CF** [comment]
Using **_screen_** command might help.

**Comment by A135CF** [comment]
> Using **_screen_** command might help.

The command **_tmux_** would also help to solve your problem. You might use it by following the instructions in this [link](https://www.ruanyifeng.com/blog/2019/10/tmux.html).
